import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import ImgContextProvider from '@/context/img-context'
import PopUpContextProvider from '@/context/popup-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Unsplash',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): React.JSX.Element {
  return (
    <ImgContextProvider>
      <PopUpContextProvider>
        <html lang="en">
          <body className={inter.className} >
              {children}
          </body>
        </html>
      </PopUpContextProvider>
    </ImgContextProvider>

  )
}
